language: ruby
rvm:
  # See http://rubies.travis-ci.org for Precompiled Ruby Versions
# - 2.1.1
# - 2.2.10
# - 2.3.0
  - 2.4.9
# - 2.5.0
  - 2.6.6
  - 2.7.0
# - jruby-9.0.5.0
# - jruby-9.1.9.0
before_install:
script:
  - make user-test
sudo: false
notifications:
  recipients:
    - azumakuniyuki+travis-ci.org@gmail.com
  email:
    on_success: change
    on_failure: always

