module LhostEngineTest::Private
  module X2
    IsExpected = {
      # INDEX => [['D.S.N.', 'replycode', 'REASON', 'hardbounce', 'toxic'], [...]]
      '1001'  => [['5.7.1',   '554', 'norelaying',      false,  true]],
      '1002'  => [['5.0.910', '',    'filtered',        false, false]],
      '1003'  => [['5.0.910', '',    'filtered',        false, false]],
      '1004'  => [['5.0.910', '',    'filtered',        false, false],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.910', '',    'filtered',        false, false]],
      '1005'  => [['5.0.947', '',    'expired',         false, false]],
      '1006'  => [['5.1.2',   '',    'hostunknown',      true,  true]],
      '1007'  => [['5.0.947', '',    'expired',         false, false]],
      '1008'  => [['4.4.1',   '',    'expired',         false, false]],
      '1009'  => [['5.0.922', '',    'mailboxfull',     false, false]],
      '1010'  => [['5.0.921', '',    'suspend',         false,  true]],
      '1011'  => [['5.0.922', '',    'mailboxfull',     false, false],
                  ['5.0.922', '',    'mailboxfull',     false, false]],
      '1012'  => [['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true]],
      '1013'  => [['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true]],
      '1014'  => [['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true]],
      '1015'  => [['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true]],
      '1016'  => [['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true]],
      '1017'  => [['5.0.910', '',    'filtered',        false, false],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.910', '',    'filtered',        false, false]],
      '1018'  => [['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true]],
      '1019'  => [['5.0.922', '',    'mailboxfull',     false, false]],
      '1020'  => [['5.0.910', '',    'filtered',        false, false]],
      '1021'  => [['5.0.910', '',    'filtered',        false, false],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.910', '',    'filtered',        false, false]],
      '1022'  => [['5.0.910', '',    'filtered',        false, false]],
      '1023'  => [['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true]],
      '1024'  => [['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true]],
      '1025'  => [['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true]],
      '1026'  => [['5.0.921', '',    'suspend',         false,  true],
                  ['5.0.921', '',    'suspend',         false,  true]],
      '1027'  => [['5.0.922', '',    'mailboxfull',     false, false],
                  ['5.0.922', '',    'mailboxfull',     false, false]],
      '1028'  => [['4.4.1',   '',    'expired',         false, false]],
      '1029'  => [['4.1.9',   '',    'expired',         false, false]],
      '1030'  => [['5.1.1',   '550', 'userunknown',      true,  true]],
      '1031'  => [['5.4.14',  '554', 'networkerror',    false, false]],
      '1032'  => [['5.4.14',  '554', 'networkerror',    false, false]],
      '1033'  => [['5.1.1',   '550', 'userunknown',      true,  true]],
    }
  end
end

