require 'spec_helper'
require 'sisimai/data'
require 'sisimai/mail'
require 'sisimai/message'

R = {
  'Sendmail' => {
    '01' => { 'status' => %r/\A5[.]1[.]1\z/, 'reason' => %r/userunknown/ },
    '02' => { 'status' => %r/\A5[.][12][.]1\z/, 'reason' => %r/(?:userunknown|filtered)/ },
    '03' => { 'status' => %r/\A5[.]1[.]1\z/, 'reason' => %r/userunknown/ },
    '04' => { 'status' => %r/\A5[.]1[.]8\z/, 'reason' => %r/rejected/ },
    '05' => { 'status' => %r/\A5[.]2[.]3\z/, 'reason' => %r/exceedlimit/ },
    '06' => { 'status' => %r/\A5[.]6[.]9\z/, 'reason' => %r/contenterror/ },
    '07' => { 'status' => %r/\A5[.]7[.]1\z/, 'reason' => %r/norelaying/ },
    '08' => { 'status' => %r/\A4[.]7[.]1\z/, 'reason' => %r/blocked/ },
    '09' => { 'status' => %r/\A5[.]7[.]9\z/, 'reason' => %r/securityerror/ },
    '10' => { 'status' => %r/\A4[.]7[.]1\z/, 'reason' => %r/blocked/ },
    '11' => { 'status' => %r/\A4[.]4[.]7\z/, 'reason' => %r/expired/ },
    '12' => { 'status' => %r/\A4[.]4[.]7\z/, 'reason' => %r/expired/ },
    '13' => { 'status' => %r/\A5[.]3[.]0\z/, 'reason' => %r/systemerror/ },
    '14' => { 'status' => %r/\A5[.]1[.]1\z/, 'reason' => %r/userunknown/ },
    '15' => { 'status' => %r/\A5[.]1[.]2\z/, 'reason' => %r/hostunknown/ },
    '16' => { 'status' => %r/\A5[.]5[.]0\z/, 'reason' => %r/blocked/ },
    '17' => { 'status' => %r/\A5[.]1[.]6\z/, 'reason' => %r/hasmoved/ },
    '18' => { 'status' => %r/\A5[.]0[.]0\z/, 'reason' => %r/mailererror/ },
    '19' => { 'status' => %r/\A5[.]2[.]0\z/, 'reason' => %r/filtered/ },
    '20' => { 'status' => %r/\A5[.]4[.]6\z/, 'reason' => %r/networkerror/ },
    '21' => { 'status' => %r/\A4[.]4[.]7\z/, 'reason' => %r/blocked/ },
    '22' => { 'status' => %r/\A5[.]1[.]6\z/, 'reason' => %r/hasmoved/ },
    '23' => { 'status' => %r/\A5[.]7[.]1\z/, 'reason' => %r/spamdetected/ },
    '24' => { 'status' => %r/\A5[.]1[.]2\z/, 'reason' => %r/hostunknown/ },
    '25' => { 'status' => %r/\A5[.]1[.]1\z/, 'reason' => %r/userunknown/ },
    '26' => { 'status' => %r/\A5[.]1[.]1\z/, 'reason' => %r/userunknown/ },
    '27' => { 'status' => %r/\A5[.]0[.]0\z/, 'reason' => %r/filtered/ },
    '28' => { 'status' => %r/\A5[.]1[.]1\z/, 'reason' => %r/userunknown/ },
    '29' => { 'status' => %r/\A4[.]5[.]0\z/, 'reason' => %r/expired/ },
    '30' => { 'status' => %r/\A4[.]4[.]7\z/, 'reason' => %r/expired/ },
    '31' => { 'status' => %r/\A5[.]7[.]0\z/, 'reason' => %r/securityerror/ },
    '32' => { 'status' => %r/\A5[.]1[.]1\z/, 'reason' => %r/userunknown/ },
    '33' => { 'status' => %r/\A5[.]7[.]1\z/, 'reason' => %r/blocked/ },
    '34' => { 'status' => %r/\A5[.]7[.]0\z/, 'reason' => %r/securityerror/ },
    '35' => { 'status' => %r/\A5[.]7[.]13\z/, 'reason' => %r/suspend/ },
  },
  'Postfix' => {
    '01' => { 'status' => %r/\A5[.]1[.]1\z/, 'reason' => %r/mailererror/ },
    '02' => { 'status' => %r/\A5[.][12][.]1\z/, 'reason' => %r/(?:filtered|userunknown)/ },
    '03' => { 'status' => %r/\A5[.]0[.]0\z/, 'reason' => %r/filtered/ },
    '04' => { 'status' => %r/\A5[.]1[.]1\z/, 'reason' => %r/userunknown/ },
    '05' => { 'status' => %r/\A4[.]1[.]1\z/, 'reason' => %r/userunknown/ },
    '06' => { 'status' => %r/\A5[.]4[.]4\z/, 'reason' => %r/hostunknown/ },
    '07' => { 'status' => %r/\A5[.]0[.]\d+\z/, 'reason' => %r/filtered/ },
    '08' => { 'status' => %r/\A4[.]4[.]1\z/, 'reason' => %r/expired/ },
    '09' => { 'status' => %r/\A4[.]3[.]2\z/, 'reason' => %r/toomanyconn/ },
    '10' => { 'status' => %r/\A5[.]1[.]8\z/, 'reason' => %r/rejected/ },
    '11' => { 'status' => %r/\A5[.]1[.]8\z/, 'reason' => %r/rejected/ },
    '12' => { 'status' => %r/\A5[.]1[.]1\z/, 'reason' => %r/userunknown/ },
    '13' => { 'status' => %r/\A5[.]2[.][12]\z/, 'reason' => %r/(?:userunknown|mailboxfull)/ },
    '14' => { 'status' => %r/\A5[.]1[.]1\z/, 'reason' => %r/userunknown/ },
    '15' => { 'status' => %r/\A4[.]4[.]1\z/, 'reason' => %r/expired/ },
    '16' => { 'status' => %r/\A5[.]1[.]6\z/, 'reason' => %r/hasmoved/ },
    '17' => { 'status' => %r/\A5[.]4[.]4\z/, 'reason' => %r/networkerror/ },
    '18' => { 'status' => %r/\A5[.]7[.]1\z/, 'reason' => %r/norelaying/ },
    '19' => { 'status' => %r/\A5[.]0[.]0\z/, 'reason' => %r/blocked/ },
    '20' => { 'status' => %r/\A5[.]0[.]\d+\z/, 'reason' => %r/onhold/ },
    '21' => { 'status' => %r/\A5[.]0[.]\d+\z/, 'reason' => %r/networkerror/ },
  },
}


